config/routes.rb
Mascotas::Application.routes.draw do
  root to: 'home#index'

  #get "/pages/*id", to:'pages#show'

  #get "profesores/new"

  get "profesores/login"
  get "estudiantes/login"
  get "profesores/logout"
  get "archivos/cargar"
  get "profesores/correo_masivo"
  get "archivos/profesor_notas"
  get "archivos/estudiante_notas"
  get "estudiantes/menu"
  get "suscripciones/inicio"

  post"profesores/create_login_profesor", to: 'profesores#create_login_profesor'
  post"archivos/subir_archivo", to:'archivos#subir_archivo'

  post 'estudiantes/create_login_estudiante', to: 'estudiantes#create_login_estudiante'

  post 'suscripciones/createSuscripcion', to: 'suscripciones#createSuscripcion'
#resources :profesores, only: [:new,:login]
#resources :contactos, only: [:new, :create]
#resources :visitantes, only: [:new, :create]

#match 'profesores/new', to: 'profesores#new', via: [:get, :post]

end

app/controllers/profesores_controller.rb
class ProfesoresController < ApplicationController

	def login 
		@profesor = Profesor.new
	end

	def create_login_profesor
		@clave = params[:clave]
		if (@clave == '1234' || @clave=='4321' || @clave=='5678')
			create_session_profesor
			render 'profesores/menu'
		else
			flash[:notice] = "clave invalida"
			render 'profesores/login'
		end
	end

	def correo_masivo
		@profesor = Profesor.new
	end

	def logout
		session['autenticado'] = false
		session['profesor'] = nil
		session['materia'] = nil
		flash[:notice] ="Vuelva Pronto"
		render 'home/index'
	end

	private
	def secure_params
		params.permit(:contraseña)
	end

	private
	def create_session_profesor
		session['autenticado'] = true

		if @clave=='1234'
			session['profesor'] = 'Ana Karina Fernandez'
			session['materia'] = 'Base de Datos' 
		end

		if  @clave=='4321'
			session['profesor'] = 'Carlo Magurno'
			session['materia'] = 'Desarrollo del Software' 
		end

		if  @clave=='5678'
			session['profesor'] = 'Jose de Sousa'
			session['materia'] = 'Desarrollo del Software' 
		end	
	end

end

app/views/profesores/correo_masivo.html.erb
<div class="row">
  <div class="large-12 columns">
      <nav class="top-bar" data-topbar>
        <ul class="title-area">
          <li class="name">
            <h1>
              <a href="#">
                Pitagoras
              </a>
            </h1>
          </li>
          <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
        </ul>
        <section class="top-bar-section">
          <ul class="left">
            <li><%= link_to 'Subir Archivos', archivos_cargar_path  %></li>
            <li><%= link_to 'Ver Notas', archivos_profesor_notas_path  %></li>
            <li><%= link_to 'Mandar Correo', profesores_correo_masivo_path  %></li>
            <li><%= link_to 'Salir', profesores_logout_path  %></li>
          </ul>
        </section>
      </nav>
    </div>
  </div>
  <br>
  <div class="row">
    <section>
      <div class="column"> 
        <h4><%= session['profesor']%>...Zona Desabilitada</h4> 
      </div> 
      <br />
      <div class="column">
        <div class="form-centered">

        </div> 
      </div> 
    </section>
  </div>
  <br> 
  <footer class="row">
    <div class="large-12 columns">
      <hr>
      <div class="row">
        <div class="large-6 columns">
          <p>© Copyright MJRuby</p>
        </div>
      </div>
    </div>
  </footer>

app/views/profesores/login.html.erb
<div class="row">
  <div class="large-12 columns">
      <nav class="top-bar" data-topbar>
        <ul class="title-area">
          <li class="name">
            <h1>
              <a href="#">
                Pitagoras
              </a>
            </h1>
          </li>
          <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
        </ul>
        <section class="top-bar-section">
          <ul class="left">
            <li><%= link_to 'Profesores', profesores_login_path  %></li>
            <li><%= link_to 'Estudiantes', estudiantes_login_path  %></li>
          </ul>
        </section>
      </nav>
    </div>
  </div>
  <br>
  <div class="row">
    <section>
      <div class="column"> 
        <h4>Ingrese al sistema</h4> 
      </div> 
      <br />
      <div class="column">
        <div class="form-centered">
          <%= form_tag({:controller => "profesores", :action => "create_login_profesor"}, method: "post") do %>
            <%= label_tag("Contraseña:") %>
            <%= password_field_tag(:clave) %>
            <%= submit_tag("Ingresar") %>
          <% end %>
        </div> 
      </div> 
    </section>
  </div>
  <br> 
  <footer class="row">
    <div class="large-12 columns">
      <hr>
      <div class="row">
        <div class="large-6 columns">
          <p>© Copyright MJRuby</p>
        </div>
      </div>
    </div>
  </footer>
    

app/views/profesores/menu.html.erb
<div class="row">
  <div class="large-12 columns">
      <nav class="top-bar" data-topbar>
        <ul class="title-area">
          <li class="name">
            <h1>
              <a href="#">
                Pitagoras
              </a>
            </h1>
          </li>
          <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
        </ul>
        <section class="top-bar-section">
          <ul class="left">
            <li><%= link_to 'Subir Archivos', archivos_cargar_path  %></li>
            <li><%= link_to 'Ver Notas', archivos_profesor_notas_path  %></li>
            <li><%= link_to 'Mandar Correo', profesores_correo_masivo_path  %></li>
            <li><%= link_to 'Salir', profesores_logout_path  %></li>
          </ul>
        </section>
      </nav>
    </div>
  </div>
  <br>
  <div class="row">
    <section>
      <div class="column"> 
        <h4>Bienvenido profesor: <%= session['profesor'] %></h4> 
      </div> 
      <br />
      <div class="column">
        <div class="form-centered">

        </div> 
      </div> 
    </section>
  </div>
  <br> 
  <footer class="row">
    <div class="large-12 columns">
      <hr>
      <div class="row">
        <div class="large-6 columns">
          <p>© Copyright MJRuby</p>
        </div>
      </div>
    </div>
  </footer>