config/routes.rb
Mascotas::Application.routes.draw do
  root to: 'home#index'

  #get "/pages/*id", to:'pages#show'

  #get "profesores/new"

  get "profesores/login"
  get "estudiantes/login"
  get "profesores/logout"
  get "archivos/cargar"
  get "profesores/correo_masivo"
  get "archivos/profesor_notas"
  get "archivos/estudiante_notas"
  get "estudiantes/menu"
  get "suscripciones/inicio"

  post"profesores/create_login_profesor", to: 'profesores#create_login_profesor'
  post"archivos/subir_archivo", to:'archivos#subir_archivo'

  post 'estudiantes/create_login_estudiante', to: 'estudiantes#create_login_estudiante'

  post 'suscripciones/createSuscripcion', to: 'suscripciones#createSuscripcion'
#resources :profesores, only: [:new,:login]
#resources :contactos, only: [:new, :create]
#resources :visitantes, only: [:new, :create]

#match 'profesores/new', to: 'profesores#new', via: [:get, :post]

end

app/models/archivo.rb
class Archivo < ActiveRecord::Base
	has_no_table

	column :ruta, :string

	def validar_extension (archivo)
		nombre = archivo.original_filename
		$extension = nombre.slice(nombre.rindex("."),nombre.length).downcase
		if ($extension == ".xls" || $extension ==".xlsx")
			true
		else
			false
		end

	end

	def subirArchivo(archivo , materia)
       leerExcel(archivo.original_filename)
       #Con la clave del profesor conoceremos su materia
       m=materia

       conexion = GoogleDrive.login(ENV["GMAIL_USERNAME"], ENV["GMAIL_PASSWORD"]) 
       archivo = conexion.spreadsheet_by_title('Materia')
       
       if archivo.nil? 
          archivo= conexion.create_spreadsheet('Materia') 
       end 

       numeroHojaTrabajo=0
       hojaTrabajo = archivo.worksheets[numeroHojaTrabajo] 
       tituloHojaTrabajo=archivo.worksheets[numeroHojaTrabajo].title
   
       while(!(hojaTrabajo.nil?)and((tituloHojaTrabajo<=>m)!=0)) do
           numeroHojaTrabajo=numeroHojaTrabajo+1
           hojaTrabajo = archivo.worksheets[numeroHojaTrabajo]
           if !(hojaTrabajo.nil?) 
           tituloHojaTrabajo=archivo.worksheets[numeroHojaTrabajo].title
         end
       end    
      

      auxiliar=numeroHojaTrabajo
      if hojaTrabajo.nil? 
         puts 'no existe'
         archivo.add_worksheet(m,1,1)
         tituloHojaTrabajo=archivo.worksheets[numeroHojaTrabajo].title
         hojaTrabajo=archivo.worksheets[numeroHojaTrabajo]
         controlador=0

         else
          hojaTrabajo.delete
          archivo.add_worksheet(m,1,1)
          tituloHojaTrabajo=archivo.worksheets[archivo.worksheets.length-1].title
          hojaTrabajo=archivo.worksheets[archivo.worksheets.length-1]
      end

      puts hojaTrabajo.title

      contador=0  
      for i in (1.. ($listaValores.length/7))
        last_row = 1 + hojaTrabajo.num_rows
        for j in (1 .. 7)
           hojaTrabajo[last_row, j] = $listaValores[contador]
          contador=contador+1
         end  
       end 
    hojaTrabajo.save 
end 

  	def leerExcel (archivo)
   		$listaValores=[] 

   		if ($extension!= ".xls")
			oo = Roo::Excel.new("#{Rails.root}/public/archivos/"+archivo)
		end

		if ($extension!=".xlsx")
			oo = Roo::Excel.new("#{Rails.root}/public/archivos/"+archivo)
		end
   		

   		oo.default_sheet = oo.sheets.first
   		contador=0
   		valor=''
   		for i in (1 .. oo.last_row)
      		for j in (1 .. oo.last_column)
       			$listaValores[contador]= oo.cell(i,j)
       			puts $listaValores[contador]
       			contador=contador+1
   			end
  		end
  	end


    def leerNotasDeMiMateria (materia)
      $listaAlumnos=[]
      conexion = GoogleDrive.login(ENV["GMAIL_USERNAME"], ENV["GMAIL_PASSWORD"]) 
      archivo = conexion.spreadsheet_by_title('Materia')
     

       numeroHojaTrabajo=0
       hojaTrabajo = archivo.worksheets[numeroHojaTrabajo] 
       tituloHojaTrabajo=archivo.worksheets[numeroHojaTrabajo].title

       while(!(hojaTrabajo.nil?))do
          if (archivo.worksheets[numeroHojaTrabajo].title == materia)
            cantidadAlumno=0
            for i in (2 .. hojaTrabajo.num_rows)
                $listaAlumnos[cantidadAlumno]=[hojaTrabajo[i, 1],hojaTrabajo[i, 2],hojaTrabajo[i, 3],hojaTrabajo[i, 4],hojaTrabajo[i, 5],hojaTrabajo[i, 6],hojaTrabajo[i, 7]]
                cantidadAlumno=cantidadAlumno+1
            end 
            break
          end
           numeroHojaTrabajo=numeroHojaTrabajo+1
           hojaTrabajo = archivo.worksheets[numeroHojaTrabajo]
       end    
    end

     def validarCedula(cedula)
        listaMaterias=[]
        conexion = GoogleDrive.login(ENV["GMAIL_USERNAME"], ENV["GMAIL_PASSWORD"]) 
        archivo = conexion.spreadsheet_by_title('Materia')
     

        numeroHojaTrabajo=0
        hojaTrabajo = archivo.worksheets[numeroHojaTrabajo] 
        tituloHojaTrabajo=archivo.worksheets[numeroHojaTrabajo].title
        while(!(hojaTrabajo.nil?))do
           for i in (2 .. hojaTrabajo.num_rows)
              if(hojaTrabajo[i, 3]==cedula)
                return true
              end
            end 
           numeroHojaTrabajo=numeroHojaTrabajo+1
           hojaTrabajo = archivo.worksheets[numeroHojaTrabajo]
        end  
      return false 
    end


    def leerNotasCedula (cedula)
      $listaMaterias=[]
      conexion = GoogleDrive.login(ENV["GMAIL_USERNAME"], ENV["GMAIL_PASSWORD"]) 
      archivo = conexion.spreadsheet_by_title('Materia')
     

       numeroHojaTrabajo=0
       hojaTrabajo = archivo.worksheets[numeroHojaTrabajo] 
       tituloHojaTrabajo=archivo.worksheets[numeroHojaTrabajo].title
       cantidadMateria=0
       while(!(hojaTrabajo.nil?))do
           for i in (2 .. hojaTrabajo.num_rows)
              if(hojaTrabajo[i, 3]== cedula)
                $listaMaterias[cantidadMateria]=[archivo.worksheets[numeroHojaTrabajo].title,hojaTrabajo[i, 4],hojaTrabajo[i, 5],hojaTrabajo[i, 6],hojaTrabajo[i, 7]]
                cantidadMateria=cantidadMateria+1
                break
              end
            end 
           numeroHojaTrabajo=numeroHojaTrabajo+1
           hojaTrabajo = archivo.worksheets[numeroHojaTrabajo]
       end 
    end

end

app/controllers/archivos_controller.rb
class ArchivosController < ApplicationController

	def cargar
		@archivo=Archivo.new
	end

	def subir_archivo
		@archivo=Archivo.new(secure_params)
		subir=params[:archivo]
		if (@archivo.validar_extension(subir))
			materia = session["materia"]
			@archivo.subirArchivo(subir,materia)
			flash[:notice]= "Archivo subido exitosamente"
			render "profesores/menu"
		else
			flash[:notice]= "Extension de archivo invalido"
			render "archivos/cargar"
		end
	end

	def profesor_notas
		@archivo = Archivo.new
		materia = session["materia"]
		@archivo.leerNotasDeMiMateria(materia)
	end

	def estudiante_notas
		@archivo = Archivo.new
		cedula = session["cedula"]
		if (@archivo.validarCedula(cedula))
			@archivo.leerNotasCedula(cedula)
		else
			flash[:notice]="Usted no pertence a ninguna materia"
			render "estudiantes/menu"
		end
		
	end

	private
	def secure_params
		params.permit(:ruta)
	end

end

app/views/archivos/cargar.html.erb
<div class="row">
  <div class="large-12 columns">
      <nav class="top-bar" data-topbar>
        <ul class="title-area">
          <li class="name">
            <h1>
              <a href="#">
                Pitagoras
              </a>
            </h1>
          </li>
          <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
        </ul>
        <section class="top-bar-section">
          <ul class="left">
            <li><%= link_to 'Subir Archivos', archivos_cargar_path  %></li>
            <li><%= link_to 'Ver Notas', archivos_profesor_notas_path  %></li>
            <li><%= link_to 'Mandar Correo', profesores_correo_masivo_path  %></li>
            <li><%= link_to 'Salir', profesores_logout_path  %></li>
          </ul>
        </section>
      </nav>
    </div>
  </div>
  <br>
  <div class="row">
    <section>
      <div class="column"> 
        <p><h4><%= session['profesor'] %></h4></p>
        <p>Subir archivo: </p>
      </div> 
      <br />
      <div class="column">
        <div class="form-centered">
          <%= form_tag({:controller => "archivos", :action => "subir_archivo"}, :method =>"post", :multipart => "true") do %>
             <input type="file" id="<%= :archivo %>" name="<%= :archivo %>" value="<%= :archivo %>" accept="application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet">
             <%= submit_tag "Subir" %>
          <% end %>
        </div> 
      </div> 
    </section>
  </div>
  <br> 
  <footer class="row">
    <div class="large-12 columns">
      <hr>
      <div class="row">
        <div class="large-6 columns">
          <p>© Copyright MJRuby</p>
        </div>
      </div>
    </div>
  </footer>

app/views/archivos/estudiante_notas.html.erb
<div class="row">
  <div class="large-12 columns">
      <nav class="top-bar" data-topbar>
        <ul class="title-area">
          <li class="name">
            <h1>
              <a href="#">
                Pitagoras
              </a>
            </h1>
          </li>
          <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
        </ul>
        <section class="top-bar-section">
          <ul class="left">
            <li><%= link_to 'Notas', archivos_estudiante_notas_path  %></li>
            <li><%= link_to 'Subscripción a correos', suscripciones_inicio_path  %></li>
          </ul>
        </section>
      </nav>
    </div>
  </div>
  <br>
  <div class="row">
    <section>
      <div class="column">
        <div class="form-centered">
          <table>
            <thead>
              <th>Materia</th>
              <th>Nota 1</th>
              <th>Nota 2</th>
              <th>Nota 3</th>
              <th>Final</th>
            </thead>
            <tbody>
              <% for notas in $listaMaterias %>
              <tr>
                <% for datos in notas %>
                  <td><%=datos%></td>
                <% end %>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div> 
      </div> 
    </section>
  </div>
  <br> 
  <footer class="row">
    <div class="large-12 columns">
      <hr>
      <div class="row">
        <div class="large-6 columns">
          <p>© Copyright MJRuby</p>
        </div>
      </div>
    </div>
  </footer>

app/views/archivos/profesor_notas.html.erb
<div class="row">
  <div class="large-12 columns">
      <nav class="top-bar" data-topbar>
        <ul class="title-area">
          <li class="name">
            <h1>
              <a href="#">
                Pitagoras
              </a>
            </h1>
          </li>
          <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
        </ul>
        <section class="top-bar-section">
          <ul class="left">
            <li><%= link_to 'Subir Archivos', archivos_cargar_path  %></li>
            <li><%= link_to 'Ver Notas', archivos_profesor_notas_path %></li>
            <li><%= link_to 'Mandar Correo', profesores_correo_masivo_path  %></li>
            <li><%= link_to 'Salir', profesores_logout_path  %></li>
          </ul>
        </section>
      </nav>
    </div>
  </div>
  <br>
  <div class="row">
    <section>
      <div class="column">
        <div class="form-centered">
          <table>
            <thead>
              <th>Nombre</th>
              <th>Apellido</th>
              <th>Cedula</th>
              <th>Nota 1</th>
              <th>Nota 2</th>
              <th>Nota 3</th>
              <th>Final</th>
            </thead>
            <tbody>
              <% for estudiante in $listaAlumnos %>
              <tr>
                <% for datos in estudiante %>
                  <td><%=datos%></td>
                <% end %>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div> 
      </div> 
    </section>
  </div>
  <br> 
  <footer class="row">
    <div class="large-12 columns">
      <hr>
      <div class="row">
        <div class="large-6 columns">
          <p>© Copyright MJRuby</p>
        </div>
      </div>
    </div>
  </footer>