config/routes.rb
Mascotas::Application.routes.draw do
  root to: 'home#index'

  #get "/pages/*id", to:'pages#show'

  #get "profesores/new"

  get "profesores/login"
  get "estudiantes/login"
  get "profesores/logout"
  get "archivos/cargar"
  get "profesores/correo_masivo"
  get "archivos/profesor_notas"
  get "archivos/estudiante_notas"
  get "estudiantes/menu"
  get "suscripciones/inicio"

  post"profesores/create_login_profesor", to: 'profesores#create_login_profesor'
  post"archivos/subir_archivo", to:'archivos#subir_archivo'

  post 'estudiantes/create_login_estudiante', to: 'estudiantes#create_login_estudiante'

  post 'suscripciones/createSuscripcion', to: 'suscripciones#createSuscripcion'
#resources :profesores, only: [:new,:login]
#resources :contactos, only: [:new, :create]
#resources :visitantes, only: [:new, :create]

#match 'profesores/new', to: 'profesores#new', via: [:get, :post]

end

app/controllers/suscripciones_controller.rb
class SuscripcionesController < ApplicationController

	def new
		@materia= Array.new
		@materia= [['Base de Datos', 0], ['Desarrollo de Softaware', 1], ['Ruby On Rails', 2]]
		@suscripcion= Suscripcion.new
		
	end

	def createSuscripcion 
		@suscripcion= Suscripcion.new(secure_params)
		if @suscripcion.valid?
			if (@suscripcion.materia == '1')
				@suscripcion.suscribete_base
			end
			if (@suscripcion.materia == '2')
				@suscripcion.suscribete_desarrollo
			end

			if (@suscripcion.materia == '3')
					@suscripcion.suscribete_ruby
			end

			#UsuarioCorreo.contacto_email(@suscripcion).deliver
			flash[:notice] = "Registrado #{@suscripcion.email} en nuestra lista de correos"
			render 'estudiantes/menu'
		else
			flash[:notice] = "No se pudo suscribir"
			render 'estudiantes/menu'
		end
	end

	private 
	def secure_params
		params.permit(:nombre,:apellido,:cedula,:materia,:email)
	end

	private
	def tipo_suscripcion_materia(materia)
		if (materia == 1)
			@suscripcion.suscribete_base
		else
			if (materia == 2)


			else (materia == 3)

			end
		end
	end


end

app/views/suscripciones/inicio.html.erb
<div class="row">
  <div class="large-12 columns">
      <nav class="top-bar" data-topbar>
        <ul class="title-area">
          <li class="name">
            <h1>
              <a href="#">
                Pitagoras
              </a>
            </h1>
          </li>
          <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
        </ul>
        <section class="top-bar-section">
          <ul class="left">
           <li><%= link_to 'Estudiante', estudiantes_menu_path%></li>
          </ul>
        </section>
      </nav>
    </div>
  </div>
  <div class="row">
    <div class="large-12 columns">
      <br/> 
     
      <br/>
      <br/>
      <br/>
    </div>
  </div>
  <% content_for :title do %>Pit&aacute;goras<% end %>
  <div class="large-12 columns">
      <div class="row">
        <div class="large-4 small-6 columns">
          <%= form_tag({:controller => "suscripciones", :action => "createSuscripcion"}, method: "post",) do %>
          	<p>Por favor ingrese..</p>
            <p align="left"> Nombre: <%= text_field_tag(:nombre) %> </p>
            <p align="left"> Apellido: <%= text_field_tag(:apellido) %> </p>
            <p align="left"> Cedula: <%= text_field_tag(:cedula) %> </p>
   			<p align="left">Materia:<%= select_tag(:materia, options_for_select([
   						['Base de Datos', '1'],['Desarrollo del Software', '2'],
   						['Ruby On Rails','3']], '0')) %></p>

   			<p align="left"> Email: <%= text_field_tag(:email) %> </p>

          	<%= submit_tag("Aceptar") %>
          <% end %>
        </div>
      </div>
    </div>

<footer class="row">
    <div class="large-12 columns">
      <hr>
      <div class="row">
        <div class="large-6 columns">
          <p>© Copyright MJRuby</p>
        </div>
      </div>
    </div>
  </footer>